### ISSUE TITLE
submit job error

### ISSUE THREAD

**Issue by WIZARD-CXY** [ms705/firmament#40]
Hello,When I get firmament up and running and try to use 
`
python scripts/job/job_submit.py localhost 8080 /bin/sleep 60
`

The command failed with below error.
`
Traceback (most recent call last):
  File "scripts/job/job_submit.py", line 1, in <module>
    from base import job_desc_pb2
ImportError: No module named base
`
And I run the command `make` in the script directory, it complained as no makefile found.

I tried several times but failed, maybe some doc error?

**Comment by ms705** [comment]
Hi!

Thanks for reporting this, we'll take a look. Sounds like we may have introduced a bug when porting the protobuf compilation for the job scripts to CMake recently.

Try running `make scripts_job` in your build root (`firmament/build` if you followed the README) -- this might generate the scripts in the right place.

**Comment by ms705** [comment]
d881e062d5ba75be481c1023359369e518d940c4 introduced a new CMake target `scripts_job` that superseded the old Makefile for the job submission script directory. However, the changes in d881e062d5ba75be481c1023359369e518d940c4 failed to add a dependency on the `scripts_job` target, so it does not build by default. [CL 265995](https://review.gerrithub.io/#/c/265995/) fixes this.

The README also erroneously refers users to run `make` in the `scripts/job` directory; this is fixed in [CL 265996](https://review.gerrithub.io/#/c/265996/).

These changes will be merged upstream after code review; leaving this open until this happens.

**Comment by ms705** [comment]
Merged. Thanks for reporting this! :)

**Comment by WIZARD-CXY** [comment]
It works
